name: 'HCL AppScan CodeSweep'
description: 'Scan for security issues in code'
branding:
  color: 'blue'
  icon: 'lock'  

runs:
  using: 'docker'
  image: 'docker://hclcr.io/appscan/appscan-src-cli:10.0.8'
