name: 'HCL AppScan Source'
description: 'Scan for security issues in code'
author: 'Florin' 
branding:
  color: 'blue'
  icon: 'lock'  
inputs:
  script-file:
    description: 'AppScan Source script file'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - script /github/workspace/${{inputs.script-file}}
